version: '3.3'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./docker/python3.10/Dockerfile
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "8888:8888"
    volumes:
      - ./:/app

  mariadb:
    container_name: mariadb
    build: 
      context: ./docker/mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:cached
#      - ./docker/mariadb/data:/var/lib/mysql:cached
